import fs from 'fs';
import path from 'path';
import YAML from 'yaml';
import { generateWorkflowCode, parseWorkflowCode } from '@n8n/workflow-sdk';
import { McpClient } from './mcp-client.js';
import { N8nCliConfig } from './config.js';
import * as output from './output.js';

export interface ReferenceWorkflowInfo {
  name: string;
  path: string;
  description: string;
}

export async function pullReferences(mcp: McpClient, config: N8nCliConfig, repoRoot: string) {
  if (!config.references || !config.references.projectId) {
    output.debug('No reference project configured. Skipping reference pull.');
    return;
  }

  const refProjId = config.references.projectId;
  const refFolderId = config.references.folderId;

  output.log(`Pulling reference workflows from project: ${config.references.projectName}...`);

  const referencesDir = path.join(repoRoot, 'n8n', 'references');
  if (fs.existsSync(referencesDir)) {
    fs.rmSync(referencesDir, { recursive: true, force: true });
  }
  fs.mkdirSync(referencesDir, { recursive: true });

  try {
    // 1. Fetch reference workflows using MCP
    const response = await mcp.callToolAndGetJson('search_workflows', {
      projectId: refProjId,
      limit: 100,
    });

    const workflows = Array.isArray(response) ? response : (response.workflows || []);
    
    // Filter by folder if configured
    let filteredWorkflows = workflows;
    if (refFolderId) {
      filteredWorkflows = workflows.filter((w: any) => w.folderId === refFolderId);
    }

    if (filteredWorkflows.length === 0) {
      output.warn('No reference workflows found matching the criteria.');
      return;
    }

    const workflowInfos: ReferenceWorkflowInfo[] = [];

    // Helper to clean up filenames
    const sanitizeFilename = (name: string) => name.replace(/[\\/:*?"<>|]/g, '_');

    for (const w of filteredWorkflows) {
      output.log(`  Pulling reference: ${w.name}...`);
      
      try {
        // Fetch full workflow details
        const details = await mcp.callToolAndGetJson('get_workflow_details', {
          id: w.id,
        });

        // Convert JSON to TS code
        const tsCode = generateWorkflowCode(details);

        // Determine directory based on folder names or folder hierarchy
        let folderSubdir = '';
        if (details.folderName) {
          folderSubdir = sanitizeFilename(details.folderName);
        } else if (config.references.folderName) {
          folderSubdir = sanitizeFilename(config.references.folderName);
        }

        const targetDir = folderSubdir ? path.join(referencesDir, folderSubdir) : referencesDir;
        fs.mkdirSync(targetDir, { recursive: true });

        const filename = `${sanitizeFilename(details.name)}.workflow.ts`;
        const relativeFilePath = folderSubdir ? `${folderSubdir}/${filename}` : filename;
        const fullPath = path.join(targetDir, filename);

        fs.writeFileSync(fullPath, tsCode, 'utf-8');

        // Extract description
        let description = details.description || '';
        if (!description) {
          // Fallback to searching the generated TS code or using a placeholder
          try {
            const parsed = parseWorkflowCode(tsCode);
            description = parsed.description || '';
          } catch (e) {
            // ignore
          }
        }

        workflowInfos.push({
          name: details.name,
          path: relativeFilePath,
          description: description || 'No description provided.',
        });
      } catch (err) {
        output.warn(`Failed to pull reference workflow '${w.name}': ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    // 2. Write index.yaml
    const indexPath = path.join(referencesDir, 'index.yaml');
    const yamlContent = YAML.stringify({ workflows: workflowInfos });
    fs.writeFileSync(
      indexPath,
      `# Auto-generated by n8ncli pull. Do not edit.\n# Read this file to find reference workflows, then read the .workflow.ts file for implementation details.\n\n${yamlContent}`,
      'utf-8'
    );
    output.log(`Reference workflows synchronized. Index generated at: n8n/references/index.yaml`);
  } catch (err) {
    output.warn(`Failed to pull references: ${err instanceof Error ? err.message : String(err)}`);
  }
}
